# Generated by Django 4.2.11 on 2024-08-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_cep_remove_pedido_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cidade',
        ),
    ]
